[package]
name = "lxddns"
version = "2.2.6"
authors = ["benaryorg <binary@benary.org>"]
edition = "2018"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
async-std = { version = "^1.10", features = ["attributes", "unstable"] }
clap = "^2.33"
env_logger = "^0.9.0"
futures = "^0.3.16"
getset = "^0.1.1"
lapin = "^1.8"
log = "^0.4.14"
regex_static = "^0.1.1"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
thiserror = "^1.0"
uuid = { version = "^0.8.2", features = ["serde", "v4"] }

