[package]
name = "lxddns"
version = "2.0.0"
authors = ["benaryorg <binary@benary.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-amqp = "^1.2"
async-std = { version = "^1.7", features = ["tokio1", "attributes", "unstable"] }
clap = "^2.33"
env_logger = "^0.8.3"
error-chain = "^0.12.4"
futures = "^0.3.14"
lapin = "^1.7"
log = "^0.4.14"
regex_static = "^0.1.1"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
uuid = { version = "^0.8.2", features = ["serde", "v4"] }

